### PR TITLE
Added nuspec file

### PR DESCRIPTION
**Pull request by ravensorb**
I created a nuspec file to allow this to be published as a nuget package

### CODE REVIEW

**Comment by nicwise** [comment]
Thanks @ravensorb !

**Comment by ggirard-distech** [comment]
Maybe not a so great idea to push a 1.0.0 version to Nuget where as the current version on Xamarin component store was 1.15...
Is it possible to main both of them in sync plz?

**Comment by ggirard-distech** [comment]
@ravensorb any update on this? same case apply to https://github.com/Redth/AndHUD/pull/15 ...

**Comment by ravensorb** [comment]
I think i turned over ownership of the nuget published file to @nicwise

**Comment by nicwise** [comment]
Yup, it's in the repo, I've just not done anything about it yet.

**Pull request merged**
